### ISSUE TITLE
Test 040 methods in variable_fields.rb

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/marc_cleanup#117]
The following methods only relate to the 040 field.
multiple_no_040?
multiple_no_040b?
missing_040c?
fix_040b

Acceptance criteria:
- [x] All above methods have 100% test coverage

**Comment by Beck-Davis** [comment]
Methods are not at 100% yet, should be able to get them completely covered on 3/18/24.

**Comment by Beck-Davis** [comment]
All 4 methods showing 100% coverage in coveralls.

@pmgreen Can you review the PR?
