### ISSUE TITLE
Make test for comp_file format for bad_008?

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/marc_cleanup#63]
Acceptance criteria:
- [x] A fixture is created with a leader (positions 6 and 7 should be `ma`) and an 008 field
- [x] Introduce an error in the 008 specific to the format
- [x] A test is created that verifies the `bad_008?` method finds the invalid 008

See https://www.loc.gov/marc/bibliographic/bdleader.html
https://www.loc.gov/marc/bibliographic/bd008.html

**Comment by Beck-Davis** [comment]
Fixture created. 
Leader positions positions 6 and 7 are `ma`
Format specific error in the 008: 'k' in 26 position

**Comment by Beck-Davis** [comment]
Fixture error changed per @mzelesky 's instructions. Created spec test for method.

**Comment by Beck-Davis** [comment]
Formatting issues in spec test resolved. Pull request is awaiting review
