### ISSUE TITLE
Make test for leader_char_errors?

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/marc_cleanup#67]
See https://github.com/pulibrary/marc_cleanup/blob/22aaa9cabb19a2f7dface6b9c0cc9384ceac00a8/lib/marc_cleanup/leader.rb#L2

Acceptance criteria:
- [ ] test coverage for https://github.com/pulibrary/marc_cleanup/blob/main/lib/marc_cleanup/leader.rb is brought up to 100%

**Comment by Beck-Davis** [comment]
Discussed the existing method with @mzelesky. `leader_char_errors` is not needed because `leader_errors` checks for the same issue in a more specific manner. We don't need to test `leader_char_errors` and should make a ticket to remove that method.
