### ISSUE TITLE
Heading punctuation patterns

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/marc_cleanup#7]
Investigate ISBD, RDA, and MARC standards for other types of punctuation errors that can occur with headings (i.e., a heading should end with a period except when X, subfield q data should always be enclosed in parentheses, etc.).

**Comment by mzelesky** [comment]
Subfield q data should always be enclosed in parentheses.

**Comment by jbaxmeyer** [comment]
Please see the document, Applying Relationship Designators in Bibliographic Records, from the PCC http://www.loc.gov/aba/pcc/sct/documents/rel-desig-guide-bib.pdf, "Punctuation and Capitalization" for guidance on punctuation to be used in conjunction with relationship designators, including commas.

**Comment by mzelesky** [comment]
Thank you for that documentation, @jbaxmeyer. I am almost done with this section of error documentation. It should be incorporated into the project tomorrow.
