### ISSUE TITLE
Test remaining 008 types for bad_008? and the fixes

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/marc_cleanup#75]
2 types of 008 have already been tested: books and computer files. However, only the error identification has been tested. All 008 types need to be tested.

Acceptance criteria:
- [x] Each type of 008 needs to be tested under `bad_008?`
- [x] Each type of 008 needs to be tested under `fix_008`
- [x] An 008 with a field length other than 40 characters is tested
- [x] `bad_008_spec.rb` should be renamed `008_spec.rb`

**Comment by Beck-Davis** [comment]
@mzelesky the `fix_comp_008` method returns the 008 with only 38 characters instead of 40.

**Comment by pmgreen** [comment]
Moved this ticket from new issues to sprint backlog because @Beck-Davis is actively working on it.

**Comment by pmgreen** [comment]
Reviewed and merged pulibrary/marc_cleanup#84
