### ISSUE TITLE
Enhance bad_008? method to return true/false in addition to the reasons why the 008 is bad

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/marc_cleanup#77]
An 008 can be invalid due to values in the 008 or the length of the 008. Knowing the reason an 008 is invalid is beneficial. The three reasons to report out are:
1. Invalid 008 length (no further testing for the 008 can occur, so this would be the only error if it were an error)
2. Invalid value in global 008 (positions 0-17, 35-39)
3. Invalid value in the specific 008 (positions 18-34)

The above strings (Invalid 008 length, Invalid value in global 008, Invalid value in specific 008) need to be reported out.

Acceptance criteria:
- [ ] bad_008? returns a hash with one key of `:invalid` (value is true or false) and one key of `:errors` (an array of strings)

**Comment by pmgreen** [comment]
Draft PR https://github.com/pulibrary/marc_cleanup/pull/124
