### ISSUE TITLE
Tests for 007 methods

### ISSUE THREAD

**Issue by Beck-Davis** [pulibrary/marc_cleanup#87]
Tests for 007 methods in fixed_fields.rb

- [x] Tests `bad_007?` for each format
- [x] Tests `fix_007` for each format

https://www.loc.gov/marc/bibliographic/bd007.html

**Comment by Beck-Davis** [comment]
The test for `bad_007?` for microform_007 is currently blocked by an issue with the `microform_007` method.

**Comment by mzelesky** [comment]
Is this ticket still needed?
