### ISSUE TITLE
Bring fixed_fields test coverage to 100% and clarify code

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/marc_cleanup#99]
- [x] Explain that kit and notated music 007s are tested with the same method
- [x] test `fixed_field_char_errors?`
- [x] move `bib_form` method from `fixed_fields.rb` to `record_level.rb`
- [x] make a test for `sparse_record?` in `record_level.rb`
- [x] remove `comp_codes_uris` from `fixed_fields.rb` (a relic of an authority control project that was moved to a separate repo)
- [x] make a test for the 008s that utilizes `cr_contents_codes`
- [x] cover all lines of `motion_pict_007`
- [x] cover all lines of `bad_007?`
- [x] cover all lines of `fix_remote_007`
- [x] cover all lines of `fix_contents_chars`
- [x] remove the `else` condition from the specific_008 section of `fix_008` (all possible permutations are addressed)

**Comment by Beck-Davis** [comment]
`fix_remote_007` should be `fix_sound_record_007`

**Comment by Beck-Davis** [comment]
Tests are not reaching line 1627 of fixed_fields.rb
